---
oracle_sw_source_local: "/u/app/oracle/distr"
oracle_rsp_dir: "{{ oracle_sw_source_local }}/rsp"
#!!!
oracle_network_files: "{{ oracle_home }}/network/admin"

########distrib location#######
nfs_sw_path: /net/oraclenas/distrib/Oracle/01_Database
sw_images:
  - version: 12.2.0.1
    Linux_x86_64:
      - "{{ nfs_sw_path }}/12cR2.EE.SE2/Linux.x86_64/linuxx64_12201_database.zip"
    Solaris_sparc64:
      - "{{ nfs_sw_path }}/12cR2.EE.SE2/Solaris.Sparc64/solarissparc64_12202_database.zip"
    Solaris_x86_64:
      - "{{ nfs_sw_path }}/12cR2.EE.SE2/Solaris.x86_64/solarisx64_12202_database.zip"
  - version: 12.1.0.2
    Solaris_sparc64:
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Solaris.sparc64/p21419221_121020_SOLARIS64_1of10.zip"
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Solaris.sparc64/p21419221_121020_SOLARIS64_2of10.zip"
    Solaris_x86_64:
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Solaris.x86_64/p21419221_121020_Solaris86-64_1of10.zip"
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Solaris.x86_64/p21419221_121020_Solaris86-64_2of10.zip"
    Linux_x86_64:
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Linux.x86_64/p21419221_121020_Linux-x86-64_1of10.zip"
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Linux.x86_64/p21419221_121020_Linux-x86-64_2of10.zip"
  - version: 12.1.0.2se
    Linux_x86_64:
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Linux.x86_64/p21419221_121020_Linux-x86-64_3of10.zip"
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Linux.x86_64/p21419221_121020_Linux-x86-64_4of10.zip"
    Solaris_sparc64:
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Solaris.sparc64/p21419221_121020_SOLARIS64_3of10.zip"
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Solaris.sparc64/p21419221_121020_SOLARIS64_4of10.zip"
    Solaris_x86_64:
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Solaris.x86_64/p21419221_121020_Linux-Solaris86-64_3of10.zip"
      - "{{ nfs_sw_path }}/12cR1.EE.SE2/Solaris.x86_64/p21419221_121020_Linux-Solaris86-64_4of10.zip"
  - version: 11.2.0.4
    Solaris_sparc64:
      - "{{ nfs_sw_path }}/11gR2/Solaris.sparc64/11.2.0.4/p13390677_112040_SOLARIS64_1of7.zip"
      - "{{ nfs_sw_path }}/11gR2/Solaris.sparc64/11.2.0.4/p13390677_112040_SOLARIS64_2of7.zip"
    Solaris_x86_64:
      - "{{ nfs_sw_path }}/11gR2/Solaris.x86_64/11.2.0.4/p13390677_112040_Solaris86-64_1of6.zip"
      - "{{ nfs_sw_path }}/11gR2/Solaris.x86_64/11.2.0.4/p13390677_112040_Solaris86-64_2of6.zip"
    Linux_x86_64:
      - "{{ nfs_sw_path }}/11gR2/Linux.x86_64/11.2.0.4/p13390677_112040_Linux-x86-64_1of7.zip"
      - "{{ nfs_sw_path }}/11gR2/Linux.x86_64/11.2.0.4/p13390677_112040_Linux-x86-64_2of7.zip"
  - version: 11.2.0.4se
    Solaris_sparc64:
      - "{{ nfs_sw_path }}/11gR2/Solaris.sparc64/11.2.0.4/p13390677_112040_SOLARIS64_1of7.zip"
      - "{{ nfs_sw_path }}/11gR2/Solaris.sparc64/11.2.0.4/p13390677_112040_SOLARIS64_2of7.zip"
    Solaris_x86_64:
      - "{{ nfs_sw_path }}/11gR2/Solaris.x86_64/11.2.0.4/p13390677_112040_Solaris86-64_1of6.zip"
      - "{{ nfs_sw_path }}/11gR2/Solaris.x86_64/11.2.0.4/p13390677_112040_Solaris86-64_2of6.zip"
    Linux_x86_64:
      - "{{ nfs_sw_path }}/11gR2/Linux.x86_64/11.2.0.4/p13390677_112040_Linux-x86-64_1of7.zip"
      - "{{ nfs_sw_path }}/11gR2/Linux.x86_64/11.2.0.4/p13390677_112040_Linux-x86-64_2of7.zip"
      
######## Version of oracle rdbms for installation #########
all_homes:
  12.2.0.1:
    oracle_home: "{{ homes_path_override['12.2.0.1'] | default(oracle_base + '/product/12.2.0.1/dbhome_1') }}"
  12.1.0.2:
    oracle_home: "{{ homes_path_override['12.1.0.2'] | default(oracle_base + '/product/12.1.0.2/dbhome_1') }}"
  12.1.0.2j7:
    oracle_home: "{{ homes_path_override['12.1.0.2j7'] | default(oracle_base + '/product/12.1.0.2j7/dbhome_1') }}"
  12.1.0.2se:
    oracle_home: "{{ homes_path_override['12.1.0.2se'] | default(oracle_base + '/product/12.1.0.2se/dbhome_1') }}"
  11.2.0.4:
    oracle_home: "{{ homes_path_override['11.2.0.4'] | default(oracle_base + '/product/11.2.0.4/dbhome_1') }}"
  11.2.0.4se:
    oracle_home: "{{ homes_path_override['11.2.0.4se'] | default(oracle_base + '/product/11.2.0.4se/dbhome_1') }}"

# Ограничивает набор OH для инсталяции
# Можно переопределить в extra vars. Значение по умолчанию пустой список
# install_only_version:
#   - 12.1.0.2
#   - 11.2.0.4
install_only_version:
  - 12.2.0.1
  - 12.1.0.2
  - 11.2.0.4
# Значение по умолчанию для homes_path_override - пустой словарь.
# Задается в extra vars.
# Используется для переопределения путей для OH указанных версий.
# Пример (закомментирован):
#
homes_path_override: []
#  12.1.0.2: oracle_base + '/product/12.1.0.2/dbhome_2'
#  11.2.0.4se: oracle_base + '/product/11.2.0.4se/dbhome_3'

#homes_path_override: {}
    
# Формирование финального набора OH для обработки.
# Здесь происходит фильтрация all_homes по ключам из homes_for_processing с записью результата в homes.
homes: "{{ dict(install_only_version | zip( install_only_version | map('extract', all_homes) )) }}"

  
